---

- name: Checking whether ThinLinc is installed
  command: "rpm -q thinlinc-vsm-{{ thinlinc_version }}-{{ thinlinc_build }}"
  args:
    warn: False
  register: thinlinc_packages_installed
  failed_when: ( thinlinc_packages_installed.rc not in [0, 1] )
  changed_when: False
  check_mode: no

