---
# The apt provider actually calls dpkg for local packages, which isn't
# clever enough to handle our upgrades:
# https://github.com/ansible/ansible/issues/77150

- name: Install ThinLinc Software
  command: "/usr/bin/apt install -y -o \"Dpkg::Options::=--no-debsig\" -o \"Dpkg::Options::=--force-confold\" {{ ' '.join(thinlinc_packages) }}"
  notify: run tl-setup
