---
- name: Locate 32-bit packages
  find:
    paths: "/root/tl-{{ thinlinc_version }}-server/packages"
    patterns:
      - "thinlinc*i386.deb"
      - "thinlinc*all.deb"
  when: ansible_architecture == 'i386'
  register: _packages_32bit

- name: Locate 64-bit packages
  find:
    paths: "/root/tl-{{ thinlinc_version }}-server/packages"
    patterns:
      - "thinlinc*amd64.deb"
      - "thinlinc*all.deb"
  when: ansible_architecture == 'x86_64'
  register: _packages_64bit

# The apt provider actually calls dpkg for local packages, which isn't
# clever enough to handle our upgrades:
# https://github.com/ansible/ansible/issues/77150
#
- name: Install 32-bit ThinLinc Software
  command: >
    /usr/bin/apt-get install -y
    -o Dpkg::Options::="--no-debsig"
    -o Dpkg::Options::="--force-confold"
    {{ _packages_32bit.files | map(attribute='path') | join(' ') }}
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: _packages_32bit is not skipped
  notify: run tl-setup

- name: Install 64-bit ThinLinc Software
  command: >
      /usr/bin/apt-get install -y
      -o Dpkg::Options::="--no-debsig"
      -o Dpkg::Options::="--force-confold"
      {{ _packages_64bit.files | map(attribute='path') | join(' ') }}
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: _packages_64bit is not skipped
  notify: run tl-setup
