---

- name: Installing pre-requisites
  package:
    name: unzip
    state: present

- name: Checking which packages are installed
  package_facts:

- name: Checking for installed ThinLinc packages
  set_fact:
    thinlinc_packages_installed: true
  when: "('thinlinc-vsm' in ansible_facts.packages) and
         (ansible_facts.packages['thinlinc-vsm'][0]['version'] == (thinlinc_version  + '-' + thinlinc_build))"

- name: Installing ThinLinc packages
  block:
    - name: Unpacking ThinLinc server bundle
      unarchive:
        src: "{{ thinlinc_server_bundle }}"
        dest: /root
    - name: Checking if rpm platform
      set_fact:
        _tl_pkg_fmt: rpm
      when: ansible_os_family in ["RedHat", "Suse"]
    - name: Checking if deb platform
      set_fact:
        _tl_pkg_fmt: deb
      when: ansible_os_family in ["Debian", "Ubuntu", "Linuxmint"]
    - name: Checking which packages to install
      set_fact:
        thinlinc_packages: "{{ _thinlinc_packages[ansible_architecture][_tl_pkg_fmt] }}"
    - include_tasks: "install-thinlinc-rhel.yml"
      when: ansible_os_family == "RedHat"
    - include_tasks: "install-thinlinc-suse.yml"
      when: ansible_os_family == "Suse"
    - include_tasks: "install-thinlinc-debian.yml"
      when: ansible_os_family in ["Debian", "Ubuntu", "Linuxmint"]
  when: thinlinc_packages_installed is undefined

# Workaround for OpenSUSE Tumbleweed usr merge
# See https://www.cendio.com/bugzilla/show_bug.cgi?id=7829
- name: Copy /usr/etc/pam.d/sshd
  include_tasks: "copy_usr_etc_pam_sshd.yml"

- name: Copy in tlsetup.answers
  template:
    src: thinlinc-setup.answers.j2
    dest: /root/thinlinc-setup.answers
  notify: run tl-setup

# Force tl-setup to run here, if required
- meta: flush_handlers

- name: Configure /vsmagent/agent_hostname
  tlconfig:
    param: /vsmagent/agent_hostname
    value: "{{ thinlinc_agent_hostname or ansible_fqdn }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

- name: Configure /vsmagent/master_hostname
  tlconfig:
    param: /vsmagent/master_hostname
    value: "{{ groups['thinlinc_masters'][0] or 'localhost' }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

- name: Configure /vsmagent/allowed_clients
  tlconfig:
    param: /vsmagent/allowed_clients
    value: "{{ ' '.join(groups['thinlinc_masters']) or 'localhost' }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

- name: Configure list of agent servers
  tlconfig:
    param: /vsmserver/subclusters/Default/agents
    value: "{{ ' '.join(groups['thinlinc_agents']) or 'localhost' }}"
  notify: restart vsmserver
  when: "'thinlinc_masters' in group_names"
